[package]
name = "krist-vanity"
version = "0.1.0"
authors = ["jordin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "0.19.3"
colored = "1.9"
clap = { version = "2.33", features = ["yaml"] }
